cloud:
  aws:
    credentials:
      access-key: AKIAY
      secret-key: 8eFOh3ND/io2Wxf
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: s3-maninder78143
